
import os
os.system ('sudo apt install tor')
os.system ('clear') 
v = "\033[0;32m"
print (v+"Hillo")
print (v+"you haked Participate in this project game ouver / sasku / jukop / mo3ad / single /")
os.system ('pkg update')
x = int(input("Enter a global definition:"))
print('exemple .... 1234')
print("oki Please", x, "Wait")
s = "\033[1;91m"
print (s+"") 
os.system ('clear')
z = '\033[0;34m'
print(z+"There is a killer in your area, close windows and doors and pray that he does not find you")
print(z+'Do you think that I am your friend? I am not your true friend, your friend died. I am using his phone now')
print(z+'er who escaped from prison. If you are reading this message, he will come to you at 3 am with a saw. If you want to keep your head, send this message to fipl')
print(z+'Every time you meet 200 people on the street, there are two of them are ghosts, good night')
print(z+'There is a crazy man who broke into my house and was looking for you. I did not want to tell him where you live, but he forced me to do so, he is coming to you')
print(z+'Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied')
print(z+'Unable to lock directory /var/lib/apt/lists/')
print(z+'[~] Setting Up Environment ....')
print(z+'[~] Installation Completed !!') 
os.system ('stop')
a = int( input("You Haked Gmail (DedSec):"))
q = int( input("how old are you:"))
print("please", a, q," wait") 
os.system ('sudo apt install upgrade')
os.system ('clear')
r ="\033[1;33m"
print(r+"open /dedsec haking marocoo")
b = int(input("nember de gmail:"))
print("rechrehce", b, "......")
os.system ('clear')
e = "\033[1;33m"
print(e+"jihaneegmail.com...........")
print(e+"ihaabgmail.com...........")
print(e+"jihaneegmail.com...........")  
print(e+"jihaneegmail.com...........")
print(e+"jihaneegmail.com...........")
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........")
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........") 
print(e+"jihaneegmail.com...........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
print(e+"dedsechakgnail.com.........")
os.system ('clear')
print(e+"paswword login <<<<<<< 1234tar56789")
print(e+"paswword login <<<<<<< aminamim6789")
print("paswword facke <<<<<<<< mamababa4321")
print(e+"paswword login <<<<<< 956788kk")
print(e+"paswword login <<<<<< rajawi12")
print(e+"paswword login <<<<<< adamadam56789")
print(e+"paswword login <<<<<< salim98765")
print(e+"paswword login <<<<<< 20062009")
print(e+"paswword login <<<<<< adminadmin")
print(e+"paswword  <<<<<< 123456-6789//13")


os.system ('sudo apt install ruby')
os.system ('clear')
os.system ('sudo apt install python3')
os.system ('clear')
print('i2lethal@hotmail.com / paswword <<<< dropsm7484')
